# Find more information on toml format here:  https://github.com/toml-lang/toml

modLoader="javafml"
loaderVersion="[36,)"
license="GPL-3.0 License"
issueTrackerURL="https://github.com/grim3212/AssortedWorld"

[[mods]] #mandatory
modId="assortedworld"
version="${file.jarVersion}"
displayName="Assorted World"
#updateJSONURL=""
displayURL="https://assortedmods.com/world"
logoFile="logo.png"
authors="Grim3212"
description='''
An assortment of various additions based around world generation that are Minecraft world.
'''

[[dependencies.assortedworld]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.assortedworld]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
